In [1]:
import pandas as pd
import numpy as np
import scipy

In [2]:
import binom

ModuleNotFoundError: No module named 'binom'

In [3]:
from scipy.stats import binom   #binomial distributions

In [4]:
print(binom.pmf(k=19,n=20,p=0.65))   #probability_mass_function=k, n=sample size ,
p=probability of success

0.0019518741669899225


In [5]:
print(binom.cdf(2,20,0.06))  #cummulative_density_function

0.8850275957378545


solve the binomial probability of n=20,p=40 and x=10

In [6]:
print(binom.pmf(10,20,0.4))  

0.11714155053639011


In [7]:
from scipy.stats import poisson

In [8]:
print(poisson.pmf(3,2))     #poisson distributions x=3, mean=2

0.18044704431548356


In [9]:
print(poisson.pmf(5,3.2)) 

0.11397938346351824


In [10]:
prob=poisson.cdf(7,3.2)
prob1=1-prob
print(prob1)

0.01682984174895752


In [11]:
print(poisson.pmf(10,6.4))

0.052790043854115495


uniform distributions

In [12]:
from scipy.stats import uniform

In [13]:
u=np.arange(27,40,1)

In [14]:
u

array([27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [15]:
uniform.mean(u)

array([27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5])

In [16]:
uniform.mean(loc=27,scale=12)

33.0

In [17]:
uniform.cdf(np.arange(30,36,1),loc=27,scale=12)

array([0.25      , 0.33333333, 0.41666667, 0.5       , 0.58333333,
       0.66666667])

In [18]:
prob=0.66666667-0.25
prob

0.41666667

In [19]:
uniform.mean(loc=200,scale=982)

691.0

In [20]:
uniform.std(loc=200,scale=982)

283.4789821721062

Normal distributions

In [21]:
from scipy.stats import norm

In [22]:
val,m,s=68,65.5,2.5  #val is x, m is mean, s is standard deviation

In [23]:
print(norm.cdf(val,m,s))             #finding P value

0.8413447460685429


cdf(x>val)

In [24]:
print(1-norm.cdf(val,m,s))

0.15865525393145707


cdf(val1<x<val2)

In [25]:
print(norm.cdf(val,m,s)-(norm.cdf(63,m,s)))

0.6826894921370859


p(x>700|m=494 and s=100)

In [26]:
print(1-norm.cdf(700,494,100))

0.019699270409376912


p(x<=550|m=494 and s=100)

In [27]:
print(norm.cdf(550,494,100))

0.712260281150973


p(300<x<600)
p(350<x<450)
for same mean and standard deviation

In [28]:
print(norm.cdf(600,494,100)-(norm.cdf(300,494,100)))

0.8292378553956377


In [29]:
print(norm.cdf(450,494,100)-(norm.cdf(350,494,100)))

0.2550348541262666


In [30]:
#finding z value
norm.ppf(0.95)

1.6448536269514722

In [31]:
norm.ppf(1-0.6672)

-0.43219457763866204

Hypergeometric distributions

In [32]:
from scipy.stats import hypergeom

In [33]:
pval=hypergeom.sf(0,18,3,12) 
#survival_function (n-1=0, N=total pop. ,n=sample, A=success in pop)  
#sf=1-cdf
pval

0.9754901960784306

In [34]:
pval=hypergeom.cdf(1,18,5,11)
pval

0.04738562091503275

Exponential distribution

In [35]:
from scipy.stats import expon

In [36]:
mu1=1/1.38  #mean of exp = 1/ mean of poisson
mu1

0.7246376811594204

In [37]:
expon.cdf(0.75,0,mu1)   #15/20, (upper limit,lower limit,mu1)

0.6447736190750485

T test

In [40]:
from scipy import stats
x=[10,12,20,21,22,24,18,15]
stats.ttest_1samp(x,15)

Ttest_1sampResult(statistic=1.5623450931857947, pvalue=0.1621787560592894)

population proportion

In [41]:
from statsmodels.stats.proportion import proportions_ztest

In [42]:
count=67
sample_size=120
p=0.5

In [43]:
proportions_ztest(count,sample_size,p)

(1.286806739751111, 0.1981616572238455)

DEFINE A FUNCTION FOR CALCULATING ALFA VALUE

In [44]:
def z_value(x,mu,SEM):
    z=(x-mu)/SEM
    if(z<0):
        alfa=stats.norm.cdf(z)
    else:
        alfa=1-stats.norm.cdf(z)
    print(alfa)

CALCULATING ALFA FOR DIFFERENT VALUES OF x,mu,SEM

In [45]:
x=48.5
mu=50
SEM=0.79
z_value(x,mu,SEM)

0.02879971774715278


TYPE 2 ERROR

In [53]:
def type_2(mu1,mu2,sigma,n,alfa):
    z=stats.norm.ppf(alfa)
    xbar=(mu1)+(z*sigma/np.sqrt(n))
    z2=(xbar-mu2)/(sigma/np.sqrt(n))
    if(mu1>mu2):
        beta=1-stats.norm.cdf(z2)
    else:
        beta=stats.norm.cdf(z2)
    
    print(beta)

In [54]:
type_2(13.5,7.4,9.7,60,0.05)

0.0006269625261005052


SIGMA1 AND SIGMA2 KNOWN

In [55]:
import math
from scipy import stats

In [56]:
def z_and_p(x1,x2,sigma1,sigma2,n1,n2):
    z=(x1-x2)/math.sqrt(((sigma1**2)/n1)+((sigma2**2/n2)))
    if(z>0):
        p=stats.norm.cdf(z)
    else:
        p=1-stats.norm.cdf(z)
    print(z,p)

In [57]:
z_and_p(121,112,8,8,10,10)

2.5155764746872635 0.9940581053789264


SIGMA1 AND SIGMA2 UNKNOWN AND ASSUMED EQUAL

In [58]:
b=[89.19,90.95,90.46,93.21,97.19,97.04,91.07,92.75]
a=[91.5,94.18,92.18,95.39,91.79,89.07,94.72,89.21]
stats.ttest_ind(a,b,equal_var=True)

Ttest_indResult(statistic=-0.3535908643461798, pvalue=0.7289136186068217)

In [59]:
stats.t.ppf(0.025,14)   #critical t value

-2.1447866879169277

In [60]:
stats.t.ppf(0.025,13)

-2.160368656461013

In [61]:
metro=[3,7,25,10,15,6,12,25,15,7]
rural=[48,44,40,38,33,21,20,12,1,18]
stats.ttest_ind(metro,rural,equal_var=False)

Ttest_indResult(statistic=-2.7669395785560558, pvalue=0.015827284816100885)

In [62]:
stats.ttest_rel(metro,rural)

Ttest_relResult(statistic=-2.4953831908892656, pvalue=0.034119311762520074)

In [63]:
def two_samp_proportion(p1,p2,n1,n2):
    p_pool=((p1*n2)+(p2*n1))/(n1+n2)
    x=(p_pool*(1-p_pool)*((1/n1)+(1/n2)))
    s=math.sqrt(x)
    z=(p1-p2)/s
    if(z<0):
        p_val=stats.norm.cdf(z)
    else:
        p_val=1-stats.norm.cdf(z)
    return z, p_val*2

In [64]:
two_samp_proportion(0.27,0.19,100,100)

(1.3442056254198995, 0.17888190308175567)

In [65]:
stats.norm.cdf(1.3442056254198995)

0.9105590484591222

hypothesis for two var

In [66]:
scipy.stats.f.ppf(q=1-0.05,dfn=15,dfd=10)

2.8450165269958436

In [67]:
scipy.stats.f.ppf(q=0.05,dfn=15,dfd=10)

0.3931252536255495

F-TEST EXAMPLE

In [68]:
x=[3,7,25,10,15,6,12,25,15,7]
y=[48,44,40,38,33,21,20,12,1,18]
f=np.var(x)/np.var(y)
dfn=len(x)-1
dfd=len(y)-1

In [69]:
p_value=scipy.stats.f.cdf(f,dfn,dfd)
p_value

0.024680183438910465

DETERMINING SAMPLE SIZE FOR HYPOTHESIS TEST

In [70]:
def samplesize(alfa,beta,mu1,mu2,sigma):
    z1=-1*stats.norm.ppf(alfa)
    z2=-1*stats.norm.ppf(beta)
    n=(((z1+z2)**2)*(sigma**2))/((mu1-mu2)**2)
    print(n)

In [71]:
samplesize(0.05,0.1,12,12.75,3.2)

155.900083325938
